In [86]:
import requests
from selectolax.parser import HTMLParser
from time import gmtime
from dataclasses import dataclass

@dataclass(slots=True)
class WebData:
    age: int
    html: int

@dataclass
class LineaTabla:
    number: int
    date: None
    numero1: int
    numero2: int
    numero3: int
    numero4: int
    numero5: int
    estrella1: int
    estrella2: int


class EuroScraping:
    headers = {"User-gent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"}
    url = 'https://www.euromillones.com.es/historico/resultados-euromillones-{}.html'

    def __init__(self) -> None:
        self.content = []
        self.__get_data()

    def __get_data(self):
        with requests.Session() as s:
            for age in range(2004,gmtime().tm_year+1):
                resp = s.get(url=EuroScraping.url.format(age),headers=EuroScraping.headers).text
                self.content.append(WebData(age,resp))
    
    def parse_data(self):
        self.content

    def __str__(self) -> str:
        return self.content
    
    def __repr__(self) -> str:
        return 'Srapping done'

In [87]:
algo = EuroScraping()

In [145]:
low = list(map(lambda x: x.css('td'), rows[2:]))

In [152]:
low[23]

[<Node td>,
 <Node td>,
 <Node td>,
 <Node td>,
 <Node td>,
 <Node td>,
 <Node td>,
 <Node td>,
 <Node td>]

In [194]:
for age in algo.content: #Funciona en menores de 2011
    rows = HTMLParser(age.html).css('table:nth-child(4) tbody tr')
    #list(map(lambda x: x, rows[2:].css('td')))

    if age.age < 2013:
        for row in rows[2:]:
            try:
                print(LineaTabla(*list(map(lambda x: x.text(), row.css('td')))))
            except Exception as e:
                print(f'error: {age.age, e}')
                print('')
                print(list(map(lambda x: x.text(), row.css('td'))))
                print('______________')

LineaTabla(numero='1 ', fecha='13-feb', numero1='32', numero2='16', numero3='29', numero4='41', numero5='36', estrella1='9', estrella2='7')
LineaTabla(numero='2 ', fecha='20-feb', numero1='13', numero2='50', numero3='47', numero4='7', numero5='39', estrella1='2', estrella2='5')
LineaTabla(numero='3 ', fecha='27-feb', numero1='37', numero2='19', numero3='18', numero4='14', numero5='31', estrella1='5', estrella2='4')
LineaTabla(numero='4 ', fecha='05-mar', numero1='39', numero2='37', numero3='4', numero4='7', numero5='33', estrella1='5', estrella2='1')
LineaTabla(numero='5 ', fecha='12-mar', numero1='44', numero2='47', numero3='15', numero4='28', numero5='24', estrella1='4', estrella2='5')
LineaTabla(numero='6 ', fecha='19-mar', numero1='42', numero2='45', numero3='33', numero4='37', numero5='36', estrella1='9', estrella2='4')
LineaTabla(numero='7 ', fecha='26-mar', numero1='23', numero2='43', numero3='3', numero4='4', numero5='10', estrella1='2', estrella2='4')
LineaTabla(numero='8 ', fecha='02-abr', numero1='4', numero2='24', numero3='12', numero4='36', numero5='27', estrella1='2', estrella2='9')
LineaTabla(numero='9 ', fecha='09-abr', numero1='23', numero2='19', numero3='10', numero4='1', numero5='4', estrella1='2', estrella2='8')
LineaTabla(numero='10 ', fecha='16-abr', numero1='28', numero2='40', numero3='14', numero4='15', numero5='35', estrella1='3', estrella2='1')
LineaTabla(numero='11 ', fecha='23-abr', numero1='45', numero2='21', numero3='6', numero4='49', numero5='10', estrella1='5', estrella2='3')
LineaTabla(numero='12 ', fecha='30-abr', numero1='27', numero2='16', numero3='6', numero4='5', numero5='23', estrella1='7', estrella2='6')
LineaTabla(numero='13 ', fecha='07-may', numero1='38', numero2='36', numero3='15', numero4='16', numero5='21', estrella1='1', estrella2='5')
LineaTabla(numero='14 ', fecha='14-may', numero1='32', numero2='3', numero3='1', numero4='39', numero5='21', estrella1='2', estrella2='6')
LineaTabla(numero='15 ', fecha='21-may', numero1='37', numero2='39', numero3='29', numero4='15', numero5='49', estrella1='4', estrella2='9')
LineaTabla(numero='16 ', fecha='28-may', numero1='41', numero2='44', numero3='6', numero4='35', numero5='11', estrella1='6', estrella2='5')
LineaTabla(numero='17 ', fecha='04-jun', numero1='41', numero2='42', numero3='34', numero4='13', numero5='9', estrella1='7', estrella2='3')
LineaTabla(numero='18 ', fecha='11-jun', numero1='7', numero2='2', numero3='47', numero4='10', numero5='8', estrella1='1', estrella2='7')
LineaTabla(numero='19 ', fecha='18-jun', numero1='28', numero2='2', numero3='40', numero4='23', numero5='43', estrella1='6', estrella2='2')
LineaTabla(numero='20 ', fecha='25-jun', numero1='30', numero2='21', numero3='35', numero4='3', numero5='34', estrella1='1', estrella2='2')
LineaTabla(numero='21 ', fecha='02-jul', numero1='4', numero2='28', numero3='24', numero4='23', numero5='34', estrella1='1', estrella2='3')
LineaTabla(numero='22 ', fecha='09-jul', numero1='44', numero2='19', numero3='5', numero4='12', numero5='2', estrella1='8', estrella2='9')
LineaTabla(numero='23 ', fecha='16-jul', numero1='26', numero2='50', numero3='31', numero4='24', numero5='38', estrella1='8', estrella2='5')
LineaTabla(numero='24 ', fecha='23-jul', numero1='10', numero2='27', numero3='7', numero4='34', numero5='31', estrella1='8', estrella2='3')
LineaTabla(numero='25 ', fecha='30-jul', numero1='50', numero2='10', numero3='9', numero4='19', numero5='37', estrella1='6', estrella2='1')
LineaTabla(numero='26 ', fecha='06-ago', numero1='5', numero2='35', numero3='44', numero4='15', numero5='24', estrella1='6', estrella2='5')
LineaTabla(numero='27 ', fecha='13-ago', numero1='27', numero2='20', numero3='41', numero4='43', numero5='50', estrella1='8', estrella2='5')
LineaTabla(numero='28 ', fecha='20-ago', numero1='27', numero2='10', numero3='35', numero4='9', numero5='6', estrella1='6', estrella2='8')
LineaTabla(numero='29 ', fecha='27-ago', numero1='28', numero2='1', numero3='44', numero4='22', numero5='11', estrella1='1', estrella2='9')
LineaTabla(numero='30 ', fecha='03-sep', numero1='14', numero2='12', numero3='15', numero4='34', numero5='8', estrella1='7', estrella2='6')
LineaTabla(numero='31 ', fecha='10-sep', numero1='5', numero2='38', numero3='36', numero4='25', numero5='33', estrella1='5', estrella2='2')
LineaTabla(numero='32 ', fecha='17-sep', numero1='41', numero2='39', numero3='15', numero4='18', numero5='29', estrella1='8', estrella2='5')
LineaTabla(numero='33 ', fecha='24-sep', numero1='48', numero2='21', numero3='26', numero4='27', numero5='44', estrella1='1', estrella2='7')
LineaTabla(numero='34 ', fecha='01-oct', numero1='48', numero2='20', numero3='45', numero4='21', numero5='12', estrella1='6', estrella2='5')
LineaTabla(numero='35 ', fecha='08-oct', numero1='12', numero2='10', numero3='48', numero4='1', numero5='16', estrella1='2', estrella2='6')
LineaTabla(numero='36 ', fecha='15-oct', numero1='37', numero2='21', numero3='14', numero4='43', numero5='22', estrella1='5', estrella2='8')
LineaTabla(numero='37 ', fecha='22-oct', numero1='9', numero2='25', numero3='1', numero4='40', numero5='23', estrella1='3', estrella2='9')
LineaTabla(numero='38 ', fecha='29-oct', numero1='32', numero2='1', numero3='38', numero4='35', numero5='8', estrella1='9', estrella2='4')
LineaTabla(numero='39 ', fecha='05-nov', numero1='25', numero2='42', numero3='49', numero4='19', numero5='6', estrella1='1', estrella2='7')
LineaTabla(numero='40 ', fecha='12-nov', numero1='12', numero2='13', numero3='4', numero4='32', numero5='11', estrella1='9', estrella2='3')
LineaTabla(numero='41 ', fecha='19-nov', numero1='37', numero2='29', numero3='34', numero4='18', numero5='1', estrella1='6', estrella2='2')
LineaTabla(numero='42 ', fecha='26-nov', numero1='24', numero2='1', numero3='34', numero4='4', numero5='36', estrella1='8', estrella2='6')
LineaTabla(numero='43 ', fecha='03-dic', numero1='15', numero2='42', numero3='11', numero4='1', numero5='49', estrella1='4', estrella2='3')
LineaTabla(numero='44 ', fecha='10-dic', numero1='3', numero2='13', numero3='43', numero4='1', numero5='16', estrella1='7', estrella2='2')
LineaTabla(numero='45 ', fecha='17-dic', numero1='49', numero2='22', numero3='19', numero4='15', numero5='46', estrella1='9', estrella2='2')
LineaTabla(numero='46 ', fecha='24-dic', numero1='3', numero2='27', numero3='29', numero4='4', numero5='37', estrella1='6', estrella2='5')
LineaTabla(numero='47 ', fecha='31-dic', numero1='8', numero2='7', numero3='47', numero4='25', numero5='24', estrella1='8', estrella2='9')
LineaTabla(numero='1 ', fecha='07-ene', numero1='50', numero2='27', numero3='47', numero4='3', numero5='23', estrella1='3', estrella2='2')
LineaTabla(numero='2 ', fecha='14-ene', numero1='11', numero2='14', numero3='29', numero4='6', numero5='19', estrella1='3', estrella2='1')
LineaTabla(numero='3 ', fecha='21-ene', numero1='12', numero2='14', numero3='10', numero4='26', numero5='24', estrella1='8', estrella2='5')
LineaTabla(numero='4 ', fecha='28-ene', numero1='26', numero2='21', numero3='7', numero4='43', numero5='45', estrella1='5', estrella2='7')
LineaTabla(numero='5 ', fecha='04-feb', numero1='11', numero2='1', numero3='40', numero4='30', numero5='8', estrella1='7', estrella2='8')
LineaTabla(numero='6 ', fecha='11-feb', numero1='11', numero2='13', numero3='25', numero4='32', numero5='50', estrella1='7', estrella2='4')
LineaTabla(numero='7 ', fecha='18-feb', numero1='32', numero2='46', numero3='20', numero4='21', numero5='26', estrella1='8', estrella2='9')
LineaTabla(numero='8 ', fecha='25-feb', numero1='43', numero2='3', numero3='27', numero4='44', numero5='30', estrella1='8', estrella2='4')
LineaTabla(numero='9 ', fecha='04-mar', numero1='12', numero2='32', numero3='37', numero4='39', numero5='24', estrella1='7', estrella2='9')
LineaTabla(numero='10 ', fecha='11-mar', numero1='40', numero2='12', numero3='43', numero4='23', numero5='8', estrella1='1', estrella2='4')
LineaTabla(numero='11 ', fecha='18-mar', numero1='48', numero2='39', numero3='23', numero4='6', numero5='43', estrella1='5', estrella2='7')
LineaTabla(numero='12 ', fecha='25-mar', numero1='29', numero2='33', numero3='38', numero4='4', numero5='37', estrella1='9', estrella2='6')
LineaTabla(numero='13 ', fecha='01-abr', numero1='26', numero2='44', numero3='47', numero4='25', numero5='41', estrella1='3', estrella2='7')
LineaTabla(numero='14 ', fecha='08-abr', numero1='31', numero2='50', numero3='25', numero4='11', numero5='7', estrella1='3', estrella2='1')
LineaTabla(numero='15 ', fecha='15-abr', numero1='6', numero2='31', numero3='42', numero4='38', numero5='28', estrella1='9', estrella2='3')
LineaTabla(numero='16 ', fecha='22-abr', numero1='13', numero2='10', numero3='24', numero4='47', numero5='3', estrella1='9', estrella2='5')
LineaTabla(numero='17 ', fecha='29-abr', numero1='42', numero2='35', numero3='9', numero4='3', numero5='39', estrella1='1', estrella2='8')
LineaTabla(numero='18 ', fecha='06-may', numero1='44', numero2='21', numero3='12', numero4='7', numero5='26', estrella1='6', estrella2='8')
LineaTabla(numero='19 ', fecha='13-may', numero1='12', numero2='40', numero3='31', numero4='17', numero5='32', estrella1='9', estrella2='2')
LineaTabla(numero='20 ', fecha='20-may', numero1='28', numero2='6', numero3='47', numero4='7', numero5='13', estrella1='8', estrella2='5')
LineaTabla(numero='21 ', fecha='27-may', numero1='50', numero2='48', numero3='31', numero4='2', numero5='24', estrella1='9', estrella2='4')
LineaTabla(numero='22 ', fecha='03-jun', numero1='8', numero2='11', numero3='3', numero4='17', numero5='50', estrella1='5', estrella2='1')
LineaTabla(numero='23 ', fecha='10-jun', numero1='37', numero2='32', numero3='47', numero4='7', numero5='6', estrella1='7', estrella2='1')
LineaTabla(numero='24 ', fecha='17-jun', numero1='8', numero2='4', numero3='10', numero4='21', numero5='18', estrella1='7', estrella2='1')
LineaTabla(numero='25 ', fecha='24-jun', numero1='6', numero2='15', numero3='8', numero4='14', numero5='45', estrella1='7', estrella2='8')
LineaTabla(numero='26 ', fecha='01-jul', numero1='23', numero2='28', numero3='5', numero4='4', numero5='25', estrella1='3', estrella2='4')
LineaTabla(numero='27 ', fecha='08-jul', numero1='42', numero2='46', numero3='36', numero4='35', numero5='49', estrella1='8', estrella2='2')
LineaTabla(numero='28 ', fecha='15-jul', numero1='42', numero2='23', numero3='1', numero4='11', numero5='12', estrella1='6', estrella2='3')
LineaTabla(numero='29 ', fecha='22-jul', numero1='49', numero2='14', numero3='41', numero4='3', numero5='48', estrella1='1', estrella2='4')
LineaTabla(numero='30 ', fecha='29-jul', numero1='50', numero2='3', numero3='19', numero4='49', numero5='26', estrella1='5', estrella2='4')
LineaTabla(numero='31 ', fecha='05-ago', numero1='21', numero2='11', numero3='2', numero4='22', numero5='30', estrella1='4', estrella2='6')
LineaTabla(numero='32 ', fecha='12-ago', numero1='37', numero2='23', numero3='40', numero4='15', numero5='30', estrella1='7', estrella2='9')
LineaTabla(numero='33 ', fecha='19-ago', numero1='41', numero2='29', numero3='11', numero4='24', numero5='31', estrella1='3', estrella2='1')
LineaTabla(numero='34 ', fecha='26-ago', numero1='29', numero2='35', numero3='40', numero4='41', numero5='9', estrella1='6', estrella2='1')
LineaTabla(numero='35 ', fecha='02-sep', numero1='43', numero2='3', numero3='4', numero4='50', numero5='14', estrella1='3', estrella2='6')
LineaTabla(numero='36 ', fecha='09-sep', numero1='31', numero2='12', numero3='50', numero4='19', numero5='8', estrella1='7', estrella2='6')
LineaTabla(numero='37 ', fecha='16-sep', numero1='19', numero2='38', numero3='12', numero4='13', numero5='21', estrella1='3', estrella2='9')
LineaTabla(numero='38 ', fecha='23-sep', numero1='1', numero2='31', numero3='34', numero4='26', numero5='47', estrella1='4', estrella2='9')
LineaTabla(numero='39 ', fecha='30-sep', numero1='11', numero2='50', numero3='48', numero4='6', numero5='47', estrella1='1', estrella2='6')
LineaTabla(numero='40 ', fecha='07-oct', numero1='26', numero2='44', numero3='21', numero4='13', numero5='2', estrella1='3', estrella2='9')
LineaTabla(numero='41 ', fecha='14-oct', numero1='10', numero2='19', numero3='11', numero4='23', numero5='20', estrella1='6', estrella2='1')
LineaTabla(numero='42 ', fecha='21-oct', numero1='19', numero2='14', numero3='33', numero4='1', numero5='29', estrella1='1', estrella2='8')
LineaTabla(numero='43 ', fecha='28-oct', numero1='14', numero2='50', numero3='47', numero4='44', numero5='36', estrella1='3', estrella2='5')
LineaTabla(numero='44 ', fecha='04-nov', numero1='38', numero2='42', numero3='36', numero4='37', numero5='26', estrella1='2', estrella2='6')
LineaTabla(numero='45 ', fecha='11-nov', numero1='41', numero2='16', numero3='36', numero4='42', numero5='15', estrella1='5', estrella2='3')
LineaTabla(numero='46 ', fecha='18-nov', numero1='34', numero2='17', numero3='18', numero4='48', numero5='25', estrella1='3', estrella2='2')
LineaTabla(numero='47 ', fecha='25-nov', numero1='27', numero2='39', numero3='47', numero4='6', numero5='1', estrella1='6', estrella2='1')
LineaTabla(numero='48 ', fecha='02-dic', numero1='1', numero2='30', numero3='20', numero4='9', numero5='23', estrella1='4', estrella2='7')
LineaTabla(numero='49 ', fecha='09-dic', numero1='11', numero2='42', numero3='38', numero4='35', numero5='18', estrella1='1', estrella2='5')
LineaTabla(numero='50 ', fecha='16-dic', numero1='2', numero2='18', numero3='3', numero4='15', numero5='32', estrella1='7', estrella2='6')
LineaTabla(numero='51 ', fecha='23-dic', numero1='31', numero2='42', numero3='37', numero4='36', numero5='15', estrella1='1', estrella2='7')
LineaTabla(numero='52 ', fecha='30-dic', numero1='19', numero2='45', numero3='43', numero4='8', numero5='16', estrella1='1', estrella2='4')
LineaTabla(numero='1 ', fecha='06-ene', numero1='6', numero2='26', numero3='14', numero4='9', numero5='2', estrella1='4', estrella2='5')
LineaTabla(numero='2 ', fecha='13-ene', numero1='12', numero2='19', numero3='33', numero4='34', numero5='8', estrella1='1', estrella2='6')
LineaTabla(numero='3 ', fecha='20-ene', numero1='15', numero2='12', numero3='50', numero4='33', numero5='44', estrella1='6', estrella2='2')
LineaTabla(numero='4 ', fecha='27-ene', numero1='9', numero2='21', numero3='15', numero4='40', numero5='49', estrella1='4', estrella2='1')
LineaTabla(numero='5 ', fecha='03-feb', numero1='30', numero2='39', numero3='9', numero4='21', numero5='50', estrella1='3', estrella2='1')
LineaTabla(numero='6 ', fecha='10-feb', numero1='5', numero2='38', numero3='6', numero4='48', numero5='50', estrella1='6', estrella2='7')
LineaTabla(numero='7 ', fecha='17-feb', numero1='4', numero2='23', numero3='38', numero4='24', numero5='26', estrella1='4', estrella2='2')
LineaTabla(numero='8 ', fecha='24-feb', numero1='18', numero2='19', numero3='1', numero4='47', numero5='11', estrella1='7', estrella2='3')
LineaTabla(numero='9 ', fecha='03-mar', numero1='5', numero2='44', numero3='10', numero4='8', numero5='3', estrella1='3', estrella2='5')
LineaTabla(numero='10 ', fecha='10-mar', numero1='1', numero2='33', numero3='21', numero4='45', numero5='49', estrella1='4', estrella2='8')
LineaTabla(numero='11 ', fecha='17-mar', numero1='50', numero2='44', numero3='5', numero4='45', numero5='32', estrella1='7', estrella2='1')
LineaTabla(numero='12 ', fecha='24-mar', numero1='17', numero2='47', numero3='28', numero4='33', numero5='35', estrella1='4', estrella2='9')
LineaTabla(numero='13 ', fecha='31-mar', numero1='50', numero2='3', numero3='45', numero4='20', numero5='31', estrella1='7', estrella2='6')
LineaTabla(numero='14 ', fecha='07-abr', numero1='13', numero2='12', numero3='29', numero4='50', numero5='44', estrella1='4', estrella2='5')
LineaTabla(numero='15 ', fecha='14-abr', numero1='34', numero2='35', numero3='26', numero4='16', numero5='49', estrella1='6', estrella2='2')
LineaTabla(numero='16 ', fecha='21-abr', numero1='46', numero2='1', numero3='22', numero4='20', numero5='37', estrella1='1', estrella2='9')
LineaTabla(numero='17 ', fecha='28-abr', numero1='17', numero2='5', numero3='33', numero4='22', numero5='10', estrella1='7', estrella2='5')
LineaTabla(numero='18 ', fecha='05-may', numero1='8', numero2='50', numero3='16', numero4='4', numero5='14', estrella1='9', estrella2='3')
LineaTabla(numero='19 ', fecha='12-may', numero1='23', numero2='5', numero3='20', numero4='34', numero5='50', estrella1='1', estrella2='5')
LineaTabla(numero='20 ', fecha='19-may', numero1='49', numero2='34', numero3='25', numero4='3', numero5='5', estrella1='8', estrella2='5')
LineaTabla(numero='21 ', fecha='26-may', numero1='21', numero2='41', numero3='12', numero4='2', numero5='49', estrella1='3', estrella2='7')
LineaTabla(numero='22 ', fecha='02-jun', numero1='41', numero2='7', numero3='48', numero4='27', numero5='8', estrella1='6', estrella2='1')
LineaTabla(numero='23 ', fecha='09-jun', numero1='3', numero2='34', numero3='39', numero4='15', numero5='12', estrella1='4', estrella2='6')
LineaTabla(numero='24 ', fecha='16-jun', numero1='26', numero2='36', numero3='1', numero4='16', numero5='30', estrella1='9', estrella2='3')
LineaTabla(numero='25 ', fecha='23-jun', numero1='44', numero2='30', numero3='9', numero4='21', numero5='43', estrella1='9', estrella2='1')
LineaTabla(numero='26 ', fecha='30-jun', numero1='16', numero2='6', numero3='15', numero4='40', numero5='43', estrella1='1', estrella2='2')
LineaTabla(numero='27 ', fecha='07-jul', numero1='35', numero2='9', numero3='7', numero4='43', numero5='18', estrella1='7', estrella2='5')
LineaTabla(numero='28 ', fecha='14-jul', numero1='1', numero2='31', numero3='7', numero4='17', numero5='36', estrella1='8', estrella2='2')
LineaTabla(numero='29 ', fecha='21-jul', numero1='50', numero2='4', numero3='38', numero4='2', numero5='9', estrella1='8', estrella2='6')
LineaTabla(numero='30 ', fecha='28-jul', numero1='3', numero2='43', numero3='29', numero4='8', numero5='12', estrella1='6', estrella2='7')
LineaTabla(numero='31 ', fecha='04-ago', numero1='26', numero2='15', numero3='32', numero4='14', numero5='1', estrella1='7', estrella2='3')
LineaTabla(numero='32 ', fecha='11-ago', numero1='47', numero2='31', numero3='46', numero4='28', numero5='27', estrella1='5', estrella2='2')
LineaTabla(numero='33 ', fecha='18-ago', numero1='37', numero2='40', numero3='50', numero4='12', numero5='39', estrella1='1', estrella2='2')
LineaTabla(numero='34 ', fecha='25-ago', numero1='47', numero2='10', numero3='28', numero4='48', numero5='40', estrella1='8', estrella2='6')
LineaTabla(numero='35 ', fecha='01-sep', numero1='25', numero2='50', numero3='7', numero4='45', numero5='3', estrella1='9', estrella2='6')
LineaTabla(numero='36 ', fecha='08-sep', numero1='12', numero2='10', numero3='32', numero4='33', numero5='1', estrella1='8', estrella2='1')
LineaTabla(numero='37 ', fecha='15-sep', numero1='10', numero2='49', numero3='26', numero4='6', numero5='16', estrella1='7', estrella2='9')
LineaTabla(numero='38 ', fecha='22-sep', numero1='30', numero2='45', numero3='49', numero4='29', numero5='10', estrella1='8', estrella2='3')
LineaTabla(numero='39 ', fecha='29-sep', numero1='1', numero2='3', numero3='24', numero4='6', numero5='18', estrella1='5', estrella2='8')
LineaTabla(numero='40 ', fecha='06-oct', numero1='5', numero2='35', numero3='11', numero4='22', numero5='38', estrella1='7', estrella2='8')
LineaTabla(numero='41 ', fecha='13-oct', numero1='2', numero2='32', numero3='38', numero4='41', numero5='25', estrella1='5', estrella2='3')
LineaTabla(numero='42 ', fecha='20-oct', numero1='10', numero2='34', numero3='47', numero4='19', numero5='45', estrella1='6', estrella2='3')
LineaTabla(numero='43 ', fecha='27-oct', numero1='3', numero2='50', numero3='44', numero4='4', numero5='8', estrella1='8', estrella2='7')
LineaTabla(numero='44 ', fecha='03-nov', numero1='13', numero2='11', numero3='44', numero4='24', numero5='49', estrella1='9', estrella2='3')

In [190]:
for age in algo.content: #Funciona en menores de 2011
    rows = HTMLParser(age.html).css('table:nth-child(4) tbody tr')

    print(list(map(lambda x:x.css('td') ,rows[2:])))
    
    for row in rows[2:]:
        #print(LineaTabla(*list(map(lambda x: x.text(), row.css('td')))))
        pass
    LineaTabla(*list(map(lambda x: x.text(), row.css('td'))))

    if age.age > 2007:
        break

[[<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>]]
[[<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>]]
[[<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>], [<Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>, <Node td>]]

In [ ]:
CASO
try:
    print(LineaTabla(*list(map(lambda x: x.text(), low))))
    print(age.age, 'bien')
except Exception as e:
    print(age.age, f'error {e}')
    print(*list(map(lambda x: x.text(), low)))

if age.age > 2010:

In [155]:
list(map(lambda x: x, rows[2:]))[0].text()

'\n1 \n13-feb\n32\n16\n29\n41\n36\n9\n7\n'

In [98]:
LineaTabla(*list(map(lambda x: x.text(), low)))

LineaTabla(numero='1 ', fecha='13-feb', numero1='32', numero2='16', numero3='29', numero4='41', numero5='36', estrella1='9', estrella2='7')

In [47]:
tree.css('table tbody tr')[2].html #table > tbody > tr:nth-child(3) > td:nth-child(2)

'<tr>\n<td>1 </td>\n<td>13-feb</td>\n<td>32</td>\n<td>16</td>\n<td>29</td>\n<td>41</td>\n<td>36</td>\n<td>9</td>\n<td>7</td>\n</tr>'